### PR TITLE
Update GUI Colours to green

### LINKED ISSUE #25: Formatting of GUI
Formatting the GUI

### PR DESCRIPTION
**Pull request by cocoanautz**
Change UI colours

Closes #25

### CODE REVIEW

**Review by jasperng-nus — COMMENTED** [review]
LGTM

**Review by SherwynNg — COMMENTED** [review]
LGTM.

**Comment by AjayArvind2207** [comment]
LGTM 👍

**Comment by Xilef121** [comment]
LGTM

**Pull request merged**
